# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v9.0.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod:
  - hosts:
      - gestion.vikingosoftware.com
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: es_AR
odoo_listdb: true
odoo_listdb_staging: true
odoo_oci_image: hub.docker.com/nanosgr/do-vks
odoo_proxy: traefik
odoo_version: 17.0
paths_with_crawlers:
  - /web/image/website
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "17"
project_author: Vikingo Software
project_license: BSL-1.0
project_name: do-vks
smtp_default_from: ""
smtp_relay_host: ""
traefik_version: 2
